{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/utils.py:21: SyntaxWarning: invalid escape sequence '\\d'\n",
      "  df.Id.str.extract(\"r(\\d+)_c(\\d+)\").values.astype(int) - 1, 2, axis=-1\n",
      "/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "2024-07-24 14:27:55,637\tINFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.\n",
      "2024-07-24 14:27:55,913\tINFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from utils import *\n",
    "from grid_search import *\n",
    "from models import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_train = pd.read_csv(\"data/data_train.csv\")\n",
    "perform_grid_search_with_raytune(\"BFM\", df_train, 'grid_search_args.yaml')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div class=\"tuneStatus\">\n",
       "  <div style=\"display: flex;flex-direction: row\">\n",
       "    <div style=\"display: flex;flex-direction: column;\">\n",
       "      <h3>Tune Status</h3>\n",
       "      <table>\n",
       "<tbody>\n",
       "<tr><td>Current time:</td><td>2024-07-24 14:29:28</td></tr>\n",
       "<tr><td>Running for: </td><td>00:00:15.11        </td></tr>\n",
       "<tr><td>Memory:      </td><td>7.7/8.0 GiB        </td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "    <div class=\"systemInfo\">\n",
       "      <h3>System Info</h3>\n",
       "      Using FIFO scheduling algorithm.<br>Logical resource usage: 8.0/8 CPUs, 0/0 GPUs\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "<div class=\"messages\">\n",
       "  <h3>Messages</h3>\n",
       "  : ***LOW MEMORY*** less than 10% of the memory on this node is available for use. This can cause unexpected crashes. Consider reducing the memory used by your application or reducing the Ray object store size by setting `object_store_memory` when calling `ray.init`.\n",
       "  ... 4 more trials not shown (4 PENDING)\n",
       "  \n",
       "</div>\n",
       "<style>\n",
       ".messages {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  padding-left: 1em;\n",
       "  overflow-y: auto;\n",
       "}\n",
       ".messages h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n",
       "\n",
       "  </div>\n",
       "  <div class=\"hDivider\"></div>\n",
       "  <div class=\"trialStatus\">\n",
       "    <h3>Trial Status</h3>\n",
       "    <table>\n",
       "<thead>\n",
       "<tr><th>Trial name           </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  k</th><th style=\"text-align: right;\">  min_k</th><th>sim_options         </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>objective_55d06_00000</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\"> 40</td><td style=\"text-align: right;\">      5</td><td>{&#x27;name&#x27;: &#x27;pears_19c0</td></tr>\n",
       "<tr><td>objective_55d06_00001</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\"> 60</td><td style=\"text-align: right;\">      5</td><td>{&#x27;name&#x27;: &#x27;pears_b800</td></tr>\n",
       "<tr><td>objective_55d06_00002</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">100</td><td style=\"text-align: right;\">      5</td><td>{&#x27;name&#x27;: &#x27;pears_c7c0</td></tr>\n",
       "<tr><td>objective_55d06_00003</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">150</td><td style=\"text-align: right;\">      5</td><td>{&#x27;name&#x27;: &#x27;pears_cf40</td></tr>\n",
       "<tr><td>objective_55d06_00004</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\"> 40</td><td style=\"text-align: right;\">     10</td><td>{&#x27;name&#x27;: &#x27;pears_d240</td></tr>\n",
       "<tr><td>objective_55d06_00005</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\"> 60</td><td style=\"text-align: right;\">     10</td><td>{&#x27;name&#x27;: &#x27;pears_d540</td></tr>\n",
       "<tr><td>objective_55d06_00006</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">100</td><td style=\"text-align: right;\">     10</td><td>{&#x27;name&#x27;: &#x27;pears_d840</td></tr>\n",
       "<tr><td>objective_55d06_00007</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">150</td><td style=\"text-align: right;\">     10</td><td>{&#x27;name&#x27;: &#x27;pears_db40</td></tr>\n",
       "<tr><td>objective_55d06_00008</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\"> 40</td><td style=\"text-align: right;\">     20</td><td>{&#x27;name&#x27;: &#x27;pears_de40</td></tr>\n",
       "<tr><td>objective_55d06_00009</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\"> 60</td><td style=\"text-align: right;\">     20</td><td>{&#x27;name&#x27;: &#x27;pears_e140</td></tr>\n",
       "<tr><td>objective_55d06_00010</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">100</td><td style=\"text-align: right;\">     20</td><td>{&#x27;name&#x27;: &#x27;pears_e440</td></tr>\n",
       "<tr><td>objective_55d06_00011</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">150</td><td style=\"text-align: right;\">     20</td><td>{&#x27;name&#x27;: &#x27;pears_e700</td></tr>\n",
       "<tr><td>objective_55d06_00012</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\"> 40</td><td style=\"text-align: right;\">      5</td><td>{&#x27;name&#x27;: &#x27;pears_ea00</td></tr>\n",
       "<tr><td>objective_55d06_00013</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\"> 60</td><td style=\"text-align: right;\">      5</td><td>{&#x27;name&#x27;: &#x27;pears_ed00</td></tr>\n",
       "<tr><td>objective_55d06_00014</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">100</td><td style=\"text-align: right;\">      5</td><td>{&#x27;name&#x27;: &#x27;pears_f000</td></tr>\n",
       "<tr><td>objective_55d06_00015</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">150</td><td style=\"text-align: right;\">      5</td><td>{&#x27;name&#x27;: &#x27;pears_f300</td></tr>\n",
       "<tr><td>objective_55d06_00016</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\"> 40</td><td style=\"text-align: right;\">     10</td><td>{&#x27;name&#x27;: &#x27;pears_f600</td></tr>\n",
       "<tr><td>objective_55d06_00017</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\"> 60</td><td style=\"text-align: right;\">     10</td><td>{&#x27;name&#x27;: &#x27;pears_f900</td></tr>\n",
       "<tr><td>objective_55d06_00018</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">100</td><td style=\"text-align: right;\">     10</td><td>{&#x27;name&#x27;: &#x27;pears_fc00</td></tr>\n",
       "<tr><td>objective_55d06_00019</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">150</td><td style=\"text-align: right;\">     10</td><td>{&#x27;name&#x27;: &#x27;pears_ff00</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "  </div>\n",
       "</div>\n",
       "<style>\n",
       ".tuneStatus {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "}\n",
       ".tuneStatus .systemInfo {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus td {\n",
       "  white-space: nowrap;\n",
       "}\n",
       ".tuneStatus .trialStatus {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".tuneStatus .hDivider {\n",
       "  border-bottom-width: var(--jp-border-width);\n",
       "  border-bottom-color: var(--jp-border-color0);\n",
       "  border-bottom-style: solid;\n",
       "}\n",
       ".tuneStatus .vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33m(raylet)\u001b[0m Warning: The actor ImplicitFunc is very large (46 MiB). Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use ray.put() to put large objects in the Ray object store.\n",
      "\u001b[36m(objective pid=26111)\u001b[0m Testing {'k': 60, 'min_k': 10, 'sim_options': {'name': 'pearson_baseline', 'shrinkage': 1}}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-07-24 14:29:33,061\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_55d06_00003\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 2656, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 871, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(FileNotFoundError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=26109, ip=127.0.0.1, actor_id=13e0b9f390853beb274bc36901000000, repr=objective)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/_internal/util.py\", line 98, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 248, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/grid_search.py\", line 120, in objective\n",
      "    args = set_args(params, model_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/utils.py\", line 212, in set_args\n",
      "    with open(config_path, \"r\") as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'config_models.yaml'\n",
      "2024-07-24 14:29:33,108\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_55d06_00001\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 2656, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 871, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(FileNotFoundError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=26107, ip=127.0.0.1, actor_id=a2898df8b80d6f2400697d0f01000000, repr=objective)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/_internal/util.py\", line 98, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 248, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/grid_search.py\", line 120, in objective\n",
      "    args = set_args(params, model_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/utils.py\", line 212, in set_args\n",
      "    with open(config_path, \"r\") as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'config_models.yaml'\n",
      "2024-07-24 14:29:33,136\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_55d06_00007\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 2656, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 871, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(FileNotFoundError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=26113, ip=127.0.0.1, actor_id=45cfc68f7b009d6359a519af01000000, repr=objective)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/_internal/util.py\", line 98, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 248, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/grid_search.py\", line 120, in objective\n",
      "    args = set_args(params, model_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/utils.py\", line 212, in set_args\n",
      "    with open(config_path, \"r\") as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'config_models.yaml'\n",
      "2024-07-24 14:29:33,160\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_55d06_00006\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 2656, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 871, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(FileNotFoundError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=26112, ip=127.0.0.1, actor_id=74270f3f954b964d1f89114b01000000, repr=objective)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/_internal/util.py\", line 98, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 248, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/grid_search.py\", line 120, in objective\n",
      "    args = set_args(params, model_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/utils.py\", line 212, in set_args\n",
      "    with open(config_path, \"r\") as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'config_models.yaml'\n",
      "2024-07-24 14:29:33,182\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_55d06_00000\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 2656, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 871, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(FileNotFoundError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=26106, ip=127.0.0.1, actor_id=c536ac10c32c0bcbb0915fba01000000, repr=objective)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/_internal/util.py\", line 98, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 248, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/grid_search.py\", line 120, in objective\n",
      "    args = set_args(params, model_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/utils.py\", line 212, in set_args\n",
      "    with open(config_path, \"r\") as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'config_models.yaml'\n",
      "2024-07-24 14:29:33,191\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_55d06_00004\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 2656, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 871, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(FileNotFoundError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=26110, ip=127.0.0.1, actor_id=7b7ea2af149fefc9ca51385901000000, repr=objective)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/_internal/util.py\", line 98, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 248, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/grid_search.py\", line 120, in objective\n",
      "    args = set_args(params, model_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/utils.py\", line 212, in set_args\n",
      "    with open(config_path, \"r\") as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'config_models.yaml'\n",
      "2024-07-24 14:29:33,245\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_55d06_00002\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 2656, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 871, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(FileNotFoundError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=26108, ip=127.0.0.1, actor_id=7df783e275af101681feef5a01000000, repr=objective)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/_internal/util.py\", line 98, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 248, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/grid_search.py\", line 120, in objective\n",
      "    args = set_args(params, model_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/utils.py\", line 212, in set_args\n",
      "    with open(config_path, \"r\") as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'config_models.yaml'\n",
      "2024-07-24 14:29:33,284\tERROR tune_controller.py:1331 -- Trial task failed for trial objective_55d06_00005\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 2656, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/_private/worker.py\", line 871, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(FileNotFoundError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=26111, ip=127.0.0.1, actor_id=7a24f6506b820ff082c8cf3301000000, repr=objective)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/air/_internal/util.py\", line 98, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/opt/miniconda3/envs/myenv2/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py\", line 248, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/grid_search.py\", line 120, in objective\n",
      "    args = set_args(params, model_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/TN9/Desktop/ETHZ/MA2/CI_Project_2024/utils.py\", line 212, in set_args\n",
      "    with open(config_path, \"r\") as file:\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'config_models.yaml'\n"
     ]
    }
   ],
   "source": [
    "df_train = pd.read_csv(\"data/data_train.csv\")\n",
    "perform_grid_search_with_raytune(\"KNN\", df_train, 'grid_search_args.yaml')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_train = pd.read_csv(\"data/data_train.csv\")\n",
    "perform_grid_search_with_raytune(\"SVDsimple\", df_train, 'grid_search_args.yaml')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_train = pd.read_csv(\"data/data_train.csv\")\n",
    "perform_grid_search_with_raytune(\"SVDplusplus\", df_train, 'grid_search_args.yaml')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "myenv2",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
